config/routes.rb
D8::Application.routes.draw do

  match '/about', :to => 'pages#about'
  match '/home', :to => 'pages#home'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = 'Home'
#    if signed_in?
#      @micropost = Micropost.new
#      @feed_items = current_user.feed.paginate(:page => params[:page])
#    end
  end

  def contact
    @title = 'Contact'
  end

  def about
    @title = 'About'
  end

  def help
    @title = 'Help'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>8d</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>8d Online Woodshop</h1>
  </header>
  <div id="page">
    <div id="header_buffer">
    </div>

<%= yield %>

    <div id="footer_buffer">
    </div>
  </div>
  <footer>
    <p><%= link_to 'About us', about_path %></p>
  </footer>

</body>
</html>

app/views/pages/about.html.erb
<div class="container" id="about">
  <div class="row">
    <div class="threecol">
      <div>
      <h1>About us</h1>
      <p>Test paragraph.</p>
      </div>
    </div>
    <div class="ninecol last">
      <div>
      <h1>other column</h1>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container" id="about">
  <div class="row">
    <div class="threecol">
      <div>
      <h1>About us</h1>
      <p>Test paragraph.</p>
      </div>
    </div>
    <div class="ninecol last">
      <div>
      <h1>other column</h1>
      </div>
    </div>
  </div>
</div>